### ISSUE TITLE
Добавить свойства из корня конфигурации.

### ISSUE THREAD

**Issue by ZlobinDV** [zhichkin/DaJet#1]
При использовании сервиса /md/**ИмяБазы** возвращается JSON с описанием свойств конфигурации, например 

```
{
  "PlatformVersion": 80313,
  "CompatibilityVersion": 80317,
  "AppConfigVersion": "2.5.8.383",
  "YearOffset": 2000,
  "SyncCallsMode": 0,
  "DataLockingMode": 1,
  "ModalWindowMode": 1,
  "AutoNumberingMode": 1,
  "UICompatibilityMode": 2,
  "NamePrefix": null,
  "MapMetadataByUuid": true,
  "ExtensionCompatibility": 0,
  "Uuid": "498ce97d-6689-44e1-a350-7d98de25218c",
  "Parent": "00000000-0000-0000-0000-000000000000",
  "Name": "УправлениеПредприятием",
  "Alias": "1С:ERP Управление предприятием 2",
  "Comment": ""
}
```

Очень прошу обогатить этот JSON свойствами конфигурации:

1. Краткая информация
2. Подробная информация
3. Поставщик

Потребность вызвана специфическими отраслевыми конфигурациями (например от БИТ, которые часть значимой информации пишут именно в эти поля).

**Comment by zhichkin** [comment]
Реализовано в версии [DaJet 3.3.5](https://github.com/zhichkin/dajet/releases/tag/dajet-3.3.5)
