### ISSUE TITLE
Поддержка работы с Бизнес процессами

### ISSUE THREAD

**Issue by zloiia** [zhichkin/DaJet#10]
Доброго времени суток!
Подскажите, пожалуйста, планируется ли работа с бизнес процессами 1С ? Хотя бы в режиме чтения данных.

**Comment by zhichkin** [comment]
Здравствуйте!
Да планируется. Судя по всему ближе к концу года. Буду добавлять регистры бухгалтерии и заодно бизнес-процессы с задачами.
