### ISSUE TITLE
Тэги

### ISSUE THREAD

**Issue by Bayselonarrend** [zhichkin/DaJet#11]
Здравствуйте. У вас очень интересные проекты. Не могли бы вы добавить им в описание тэг `1c-enterprise`. Дело в том, что я веду небольшой проект - [OpenYellow](https://openyellow.org), в котором автоматически собираются open-source проекты для 1С. Но ваши не находятся по критериям поиска (язык 1С / тэг 1c-enterprise / 1С в описании) и туда они не попадают

Тэга в описании будет достаточно - проекты попадут в рейтинг и еще будет публикация в тг канале [@OpenYellowProject](https://t.me/OpenYellowProject)

Спасибо!

**Comment by zhichkin** [comment]
Спасибо большое за Ваше внимание и подсказку!
Добавил тэг `1c-enterprise` в описание репозитория.
Пользуясь случаем, хочу сказать, что проект OpenYellow - очень важное и нужно дело.
Желаю Вам успеха!
