### ISSUE TITLE
Автоскрытие уведомления об ошибке

### ISSUE THREAD

**Issue by nagorsky** [zhichkin/DaJet#12]
Добрый день. 

Когда пытаешь разобраться с работой в DaJet часто возникают ошибки. Когда исправляешь ошибку в своем скрипте и пытаешь запустить его заново - уведомление о старой ошибке продолжает висеть на экране. 
И ты уже не понимаешь - то ли у тебя исправленная версия скрипта тоже валится с ошибкой, то ли он еще не выполнился. 

Было бы здорово иметь возможность закрыть вручную уведомление об ошибке или чтобы система закрывала его автоматически  после, например 5 сек, с момента появления. 
Последним скрином привожу пример когда вроде уже ошибок нет и скрипт выполняется, но ошибка продолжает висеть и вводить в недоумение. 

![image](https://github.com/user-attachments/assets/e16b0e0a-bbe1-4822-afd5-35d81087efed)

![image](https://github.com/user-attachments/assets/a213a51d-8380-430f-8da9-e7dc29be6ab5)

**Comment by zhichkin** [comment]
Добрый день. Это ошибка браузера. Меня она тоже изрядно раздражает. Борюсь с этим перезагрузкой (обновлением) страницы - стандартная кнопка браузера в его командной панели.
