### ISSUE TITLE
Поддержка в DaJet Script  расширений 1с 

### ISSUE THREAD

**Issue by nagorsky** [zhichkin/DaJet#13]
Добрый день. 

Прошу добавить в DaJet Script  возможность писать запросы к справочникам, в которые были добавлены доп. реквизиты через механизм расширений 1С.  

Сейчас при написании select-запросов к таким справочникам DaJet Script выдает пустые выборки.  

Заранее благодарю.

**Comment by zhichkin** [comment]
Добавлено в релизе [DaJet 3.8.5](https://github.com/zhichkin/dajet/releases/tag/dajet-3.8.5)
