### ISSUE TITLE
Ошибка при попытке чтения реквизита, добавленного через расширения 1С

### ISSUE THREAD

**Issue by nagorsky** [zhichkin/DaJet#15]
Тестирую DaJet Script 3.8.5

Есть справочник, добавленный в основную конфигурацию.
Есть расширение 1С, которое добавляет доп. реквизит в этот справочник. 

До версии 3.8.5 (до добавления ?mdex)  при обращении к этому справочнику и попытке выбрать оттуда любой реквизит (не важно добавлен ли он был через расширение или через основную конфигурацию)  - выборка всегда была пустой. Т.е. dajet  делал запросы к не той sql таблице 1С. 

В версии 3.8.5 с ?mdexстало работать корректнее - т.е. запросы стали возвращать данные справочника. Но только до тех пор, пока в запросе не используешь реквизиты, добавленные через расширение 1С. 
 
Как только начинаешь запрашивать реквизит, добавленный через расширение - Dajet падает с ошибкой, см. скрин 
Убираешь этот реквизит из SELECT - начинает работать корректно.

![image](https://github.com/user-attachments/assets/2d7d8905-d9d7-4a9a-9e73-ba3fd9515564)

**Comment by zhichkin** [comment]
Добрый вечер!
1. У Вас какой тип СУБД ?
2. Можете получить текст запроса SQL из ветки "data" в DaJet Studio ? Кнопка "SQL".
![image](https://github.com/user-attachments/assets/36520bd4-fe84-4227-b2dd-f022011bce17)

**Comment by nagorsky** [comment]
1. PostgreSQL 14 for 1C
2.  

```
SELECT
_IDRRef AS Ссылка,
_Code AS Код,
_Description AS Наименование,
_Fld7048RRef AS ПациентРекомендатель  -- это реквизит ссылочного типа. Добавленный через расширение 1С.  Кстати ссылается он сам на себя, т.е. на этот же справочник, если это важно
FROM _Reference105x1
LIMIT 50;
```
Вот видео с воспроизведением проблемы:

https://github.com/user-attachments/assets/51d95131-c123-41ee-8a71-30d712bddd1b




https://github.com/user-attachments/assets/2dca8381-df48-4086-902b-36862021eb96

**Comment by zhichkin** [comment]
Прошу посмотреть выполнится ли запрос SQL к таблице _Reference105x1 в pgAmin, например. Странное что-то происходит. Поддержка расширений в DaJet, как я уже неоднократно писал, экспериментальная. Возможно есть какой-то нюанс, который мною не учтён. У Вас какая платформа 1С и в режиме какой совместимости работает конфигурация ? Попробую разобраться.

Кроме этого прошу Вас выполнить запрос в DaJet Script, завернув вызов SELECT в конструкцию обработки ошибок. Может быть так удастся докопаться до сути.
```SQL
TRY
   SELECT ...
CATCH
   PRINT ERROR_MESSAGE()
END
```

**Comment by nagorsky** [comment]
Вызываю try, но без реквизита из расширения. Выдает выборку корректно.

![image](https://github.com/user-attachments/assets/9597a3aa-9cf3-4dad-9987-e7ceef8f4c76)


Вызываю с реквизитом, пишет что Выполнено успешно, но выборки на экране не появляется. Наверное ошибка есть, он dajet ее никуда не логирует и не отображает.

![image](https://github.com/user-attachments/assets/e9eab469-9ae2-40a5-ba7a-2c2184dc3c27)

Результат выполнения запроса:

![image](https://github.com/user-attachments/assets/b1b220c9-35fc-4753-a232-47ae71c7186d)

**Comment by nagorsky** [comment]
![image](https://github.com/user-attachments/assets/c4aa858d-ee8c-45ef-8d62-d3805228a5b1)

![image](https://github.com/user-attachments/assets/b0f8a03a-7f10-400d-a81e-c86fda62d163)

**Comment by zhichkin** [comment]
Просто к сведению: когда DaJet Studio пишет "Выполнено успешно", ошибка, если она есть, логируется в ```dajet.log``` - это файл в корневом каталоге установки DaJet.

**Comment by nagorsky** [comment]
в этот файл действительно записывается строчка - [2024-11-06 15:59:48] Column must be between 0 and 3

**Comment by zhichkin** [comment]
Исправлено в релизе [DaJet 3.8.6](https://github.com/zhichkin/dajet/releases/tag/dajet-3.8.6)
