### ISSUE TITLE
Cache entry is null or expired

### ISSUE THREAD

**Issue by nagorsky** [zhichkin/DaJet#16]
Добрый вечер. 
Словил странную багу. 
Тестирую DaJet Script 3.8.5

При попытке обратиться к http://localhost:5000/md 
отображается мета-информация о базах 1С.  Все корректно.

Но при попытке обратиться к любой базе  http://localhost:5000/md/trade10-test-dev
где trade10-test-dev - это название базы, добавленной в Dajet Studio - получаю ошибку  Cache entry is null or expired
При этом в логах консоли веб-сервера никаких ошибок нет. В логах в папках dajet - тоже пусто.

Пробовал обновлять кеш средствами DaJet Studio, кнопкой обновить кеш - ошибка не уходит. 
При этом запросы к базе выполняются корректно, я могу делать выборки из такой базы без ошибок. 

![image](https://github.com/user-attachments/assets/5748d77b-0914-414e-a29c-f17e900a89b6)

![image](https://github.com/user-attachments/assets/9b087a5f-b5bd-4d00-ad4c-079d03ab2ba5)

![image](https://github.com/user-attachments/assets/2059f5e6-6d58-4eff-bba7-e143d9458555)

![image](https://github.com/user-attachments/assets/dd80d56c-94d0-421c-9ba2-b323cc4aa876)

**Comment by zhichkin** [comment]
Это старая бага =) Если развернёте ветку "Конфигурация" и далее, например, "Справочники", то кэш корректно где-то там внутри заполнится и можно без ошибок вызывать /md и так далее. Всё откладывал этот баг на потом =) Однако, учитывая Вашу заинтересованность и подробность освещения ошибок, обещаю исправить =)

**Comment by zhichkin** [comment]
Исправлено в релизе [DaJet 3.8.6](https://github.com/zhichkin/dajet/releases/tag/dajet-3.8.6)
