### ISSUE TITLE
400 BadRequest при выполнении запроса к DaJet HTTP Server

### ISSUE THREAD

**Issue by KlinskiyDD** [zhichkin/DaJet#17]
Мы развернули сервер DaJet HTTP Server в докере и активно используем его для получения актуальной информации из 1С. Запросы отправляются каждые 5 минут с помощью задачи (job).

Однако в последнее время сервер периодически возвращает ошибку 400 BadRequest. Проблема решается только перезапуском контейнера Docker.

![Логи сервера](https://github.com/user-attachments/assets/2e255cba-49a2-4909-8315-ff4dd0ee6b63)

Посмотрев код обнаружил что проблема может быть в двух случаях.  
![Участок кода, где может быть проблема](https://github.com/user-attachments/assets/449ed27c-b2ca-49f1-bd35-a0fbba065c22)

Подскажите как нам решить эту проблему?

**Comment by zhichkin** [comment]
Добрый день! В корневом каталоге установки DaJet сервера есть файл dajet.log. Это текстовой файл в формате UTF-8. Посмотрите, пожалуйста, нет ли там ошибок. Я так предполагаю, что база данных 1С перестала быть доступной.
Для более полной диагностики проблемы было бы неплохо ещё получить вот какую информацию:
- Когда вы вызываете сервис по URL, в случае ошибки, в теле ответа должно быть описание ошибки. Есть там что-то ? Можно попробовать выполнить скрипт в интерфейсе DaJet Studio и ошибка должна появиться там в нижней панели результата. Либо в средствах разработчика браузера можно посмотреть какую ошибку возвращает сервис.
- URL скрипта, как это выглядит в DaJet Studio
- Текст скрипта по этому URL
- Возможно строку подключения к базе данных
- Состав конфигурации 1С (ветка data/Конфигурация + data/Расширения). Есть вариант, что вы обращаетесь в скрипте к расширенным метаданным, а в настройке подключения к базед данных не стоит галка "Использовать расширения".

Контроллер в исходных кодах на C# вами определён вроде как правильно. В крайнем случае там можно докрутить расширенное логирование ошибки.

**Comment by zhichkin** [comment]
Интересно не совпадают ли запросы DaJet с моментами обновления конфигурации 1С. Дело в том, что некоторые обновления выполняются 1С в монопольном режиме. В таких случаях база данных будет недоступна.

**Comment by KlinskiyDD** [comment]
Выяснилось, что у нас протухла учетная запись от sql сервера. 
Обновили учетку и все заработало. 

Спасибо за оперативный ответ!
