### ISSUE TITLE
Неконтролируемый Alias

### ISSUE THREAD

**Issue by ZlobinDV** [zhichkin/DaJet#2]
При использовании сервиса /md/**ИмяБазы** возвращается JSON с описанием свойств конфигурации.

На примере конфигурации отраслевой конфигурации Центр управления лизингом (на базе 1С Бухгалтерия предприятия) возвращается JSON

```
{
  "PlatformVersion": 80313,
  "CompatibilityVersion": 80317,
  "AppConfigVersion": "3.0.128.10/3.1.53.8/3.1.0.53",
  "YearOffset": 2000,
  "SyncCallsMode": 0,
  "DataLockingMode": 1,
  "ModalWindowMode": 1,
  "AutoNumberingMode": 1,
  "UICompatibilityMode": 2,
  "NamePrefix": null,
  "MapMetadataByUuid": true,
  "ExtensionCompatibility": 0,
  "Uuid": "e0666db2-45d6-49b4-a200-061c6ba7d569",
  "Parent": "00000000-0000-0000-0000-000000000000",
  "Name": "БухгалтерияПредприятия",
  "Alias": "Enterprise Accounting, Revision 3.0",
  "Comment": ""
}
```
предполагаю что это связано с мультиязычностью конфигурации, т.к. для синонима можно задать разные значения в зависимости от локализации, пример

![image](https://user-images.githubusercontent.com/52169208/228225586-9ab2c0ea-f783-478f-9c83-15e782b01c30.png)

Хотелось бы значение поля Alias получать более управляемо, в зависимости от нужной мне локализации. 

Прошу предложить решения :)

**Comment by zhichkin** [comment]
Добрый день! Прошу прощения, что так долго не уделял внимания Вашему запросу. Никак не могу понять как сделать конфигурацию мультиязычной. Не подскажете как это сделать ? Или может быть поделитесь cf-ником ?
