### ISSUE TITLE
Авторизация Kafka

### ISSUE THREAD

**Issue by GitVVV** [zhichkin/DaJet#3]
Интересное решение, попробовал использовать. Но у нас Kafka использует авторизацию. Как добавить в параметры security.protocol, sasl.mechanism, sasl.username, sasl.password и заполнить значения?

**Comment by GitVVV** [comment]
Можно добавить редактор параметров Kafka (их же довольно много), чтобы каждый мог производить тонкую настройку под себя?
https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md

**Comment by zhichkin** [comment]
Реализовано в версии [DaJet 3.0.0](https://github.com/zhichkin/dajet/releases/tag/dajet-3.0.0).
Прошу попробовать и дать обратную связь.
