### ISSUE TITLE
Ошибка в CREATE TYPE

### ISSUE THREAD

**Issue by alex-bob-lip** [zhichkin/DaJet#4]
При попытке трансляции в SQL скрипты из документации по созданию пользовательского типа данных (Dajet 3.3.0, MSSQL) дают ошибку Unknown column data type. Независимо от выбираемых типов.

**Comment by zhichkin** [comment]
Вероятно Вы решили использовать команду IMPORT ?
Опишите, пожалуйста, подробнее свой предполагаемый сценарий использования DaJet.

**Comment by alex-bob-lip** [comment]
Да, я хотел использовать команду IMPORT совместно с CREATE TYPE. Если коротко, написав несколько запросов в Dajet, понял, что каждый раз приходится создавать виртуальные таблицы для представления перечислений, вида 
`SELECT 'НДС 10%' AS Name, Перечисление.СтавкиНДС.НДС10 AS Value
UNION ALL
SELECT 'НДС 18%', Перечисление.СтавкиНДС.НДС18
UNION ALL
SELECT 'Без НДС', Перечисление.СтавкиНДС.БезНДС`
Хотел вынести их в отдельные скрипты и переиспользовать через IMPORT. Однако наткнулся на вышеописанную ошибку при трансляции предложения CREATE TYPE в чистый SQL.

**Comment by alex-bob-lip** [comment]
> Вероятно Вы решили использовать команду IMPORT ? Опишите, пожалуйста, подробнее свой предполагаемый сценарий использования DaJet.

Пока рассматриваю 2 конкретных сценария:
1. Получение данных из 1С в мобильное приложение через WEB API.
2. Односторонний обмен из переделанной УПП в расширение для ЗУП (делаем самописный кабинет сотрудника,
хотели добавить туда данные о положенной и выданной спецодежде).

**Comment by zhichkin** [comment]
Спасибо за подробное объяснение. Ошибку команды **CREATE TYPE** постараюсь устранить в ближайшее время.

Судя по всему Вам нужно получить представление значения перечисления в человекочитаемом виде.
На мой взгляд, лучше всего эту задачу было бы решить при помощи специализированной функции, например, **NAMEOF**(_<значение перечисления>_). Аналогично функции **ПРЕДСТАВЛЕНИЕ** в языке запросов 1С. Подумаю над этим...

Примерное использование могло бы быть таким:
```SQL
SELECT Ссылка
     , Наименование
     , ЗначениеСтавкиНДС      = СтавкаНДС         -- уникальный идентификатор UUID
     , ПредставлениеСтавкиНДС = NAMEOF(СтавкаНДС) -- строковое представление значения перечисления
  FROM Справочник.Номенклатура
```

**Comment by alex-bob-lip** [comment]
>**NAMEOF**(_<значение перечисления>_). Аналогично функции **ПРЕДСТАВЛЕНИЕ** в языке запросов 1С. 

Мою задачу решит, только представление нужно тогда брать из синонима.

**Comment by zhichkin** [comment]
Могу предложить следующее временное решение пока не исправлю ошибку в следующем релизе.

Решение универсально для любых видов перечислений. В одном скрипте можно импортировать и использовать несколько переменных с типом данных UDT, то есть можно импортировать несколько перчислений в разные переменные с одним и тем же типом данных **udt_enum_values** или **dajet_enum_values**, которые приведены в качестве примера ниже.

1. Создаём UDT тип в базе данных вручную
```SQL
-- SQL Server

CREATE TYPE [udt_enum_values] AS TABLE
(
   _Value_U binary(16),
   _Name_S  nvarchar(32)
)

-- PostgreSQL (префикс dajet и нижний регистр имён обязательны)

CREATE TYPE "dajet_enum_values" AS
(
   "_value_u" bytea,
   "_name_s"  varchar(32)
)
```
2. Пишем скрипт получения значений для нужного нам перечисления (порядок следования полей **value** и **name** должен быть таким же, как при определении UDT выше)
```SQL
-- Скрипт select-enum-values

-- SQL Server
SELECT Value = Перечисление.СтавкиНДС.НДС0,   Name = 'НДС 0%'  UNION ALL
SELECT Value = Перечисление.СтавкиНДС.НДС10,  Name = 'НДС 10%' UNION ALL
SELECT Value = Перечисление.СтавкиНДС.НДС18,  Name = 'НДС 18%' UNION ALL
SELECT Value = Перечисление.СтавкиНДС.БезНДС, Name = 'Без НДС'

-- PostgreSQL
SELECT value = Перечисление.СтавкиНДС.НДС0,   name = 'НДС 0%'  UNION ALL
SELECT value = Перечисление.СтавкиНДС.НДС10,  name = 'НДС 10%' UNION ALL
SELECT value = Перечисление.СтавкиНДС.НДС18,  name = 'НДС 18%' UNION ALL
SELECT value = Перечисление.СтавкиНДС.БезНДС, name = 'Без НДС'
```
3. Импортируем и используем значения табличной переменной **enum**
```SQL

-- SQL Server
DECLARE @enum AS udt_enum_values
IMPORT "dajet://ms-demo/select-enum-values" INTO @enum
SELECT Name, Value FROM @enum AS VAT

-- PostgreSQL
DECLARE @enum AS dajet_enum_values
IMPORT "dajet://pg-demo/select-enum-values" INTO @enum
SELECT name, value FROM @enum AS VAT
```

**NB:** После создания пользовательского типа данных в базе данных необходимо перезапустить сервер DaJet.

**Comment by zhichkin** [comment]
Ошибку в исходниках нашёл и исправил. Выйдет в следующем релизе DaJet версии 3.3.1.
Временное решение описано выше. Оно протестировано уже с учётом исправленной ошибки.
Задачу закрываю.
