### ISSUE TITLE
Проблема создания видов

### ISSUE THREAD

**Issue by sacesare** [zhichkin/DaJet#5]
При  попытке создания видов во вновь созданной схеме(сервер mssql), происходит ошибка:
`
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
`
сам запрос POST /db/view/test с телом JSON:
`
{"schema":"qqq","codify":false}
`
в консоли пишет:
```
      Connection id "0HN1NIOIRR30R", Request id "0HN1NIOIRR30R:0000000E": An unhandled exception was thrown by the application.
      System.InvalidCastException: Unable to cast object of type 'System.String' to type 'DaJet.Metadata.Core.ConfigObject'.
         at DaJet.Metadata.Core.ConfigObject.GetObject(Int32[] path) in c:\1c\...\dajet-metadata\core\ConfigObject.cs:line 86
         at DaJet.Metadata.Core.Configurator.ConfigurePredefinedValues(OneDbMetadataProvider& cache, MetadataObject& metadata) in c:\1c\...\dajet-main\src\dajet-metadata\core\Configurator.cs:line 1363
```
С чем это может быть связано?
Спасибо.

**Comment by zhichkin** [comment]
Добрый день!

Опишите, пожалуйста, подробнее какие действия Вы выполнили и какую задачу при этом пытались решить, чтобы я смог воспроизвести ошибку для анализа.

Сообщите, пожалуйста, версию DaJet, Microsoft SQL Server и 1С:Предприятие, которые Вы используете.

Предварительно рекомендую попробовать использовать заглавные буквы в именах параметров, передаваемых на сервер DaJet при помощи POST запроса. То есть: Schema и Codify, а не schema и codify. Кодировка JSON должна быть UTF-8.

**Comment by sacesare** [comment]
К слову, есть еще одна нестыковка...если не развернуть хотя бы один пункт из меню "Конфигурация", а сразу пойти в "dbv"- никаких схем не будет,вернется ошибка. Даже если предварительно сделать обновление кеша для базы.
Конфиг-  1С:ERP Управление предприятием 2 (2.5.15.111),  версия платформы 8.3.23.1865, sql сервер 2017.
DaJet 3.3.0 . Вероятнее всего, что-то не так с конфигурацией...см выше ошибку из консоли.

**Comment by zhichkin** [comment]
Ошибка открытия ветки "dbv" без предварительного открытия ветки "Конфигурация" и далее, например, ветки "Справочник" это известная бага =) Всё никак руки не дойдут поправить, извините =)

Судя по ошибке из консоли, которую Вы приводили выше, происходит ошибка чтения предопределённых значений какого-то, вероятно, справочника. Без отладки я тут ничего не смогу сказать. Нужен как минимум cf-ник вашей конфигурации.

Попробовать проверить читаются ли предопределённые значения справочника DaJet в принципе можно скриптом вида:
```SQL
SELECT Справочник.Наименование.Значение
```

**Comment by zhichkin** [comment]
Спасибо большое за сообщение об ошибке!

Ошибку удалось воспроизвести на своей тестовой конфигурации.
Буду исправлять. Какой-то конкретный срок обещать не могу.

```SQL
SELECT Справочник.Тестовый.Значение1
```
**Текст ошибки:**
_Unable to cast object of type 'System.String' to type 'DaJet.Metadata.Core.ConfigObject'_

**Comment by sacesare** [comment]
Вам огромное спасибо, что пытаетесь вытянуть народ из трясины 1с, и предложить какую-то более адекватную и современную альтернативу на основе реляционной математики)
Я тоже попытаюсь подебажить, отпишитесь, если что получиться.
Кстати, на  .net 8 тоже вроде адекватно работает...

**Comment by zhichkin** [comment]
Посмотрел беглым взглядом исходники: для каких-то справочников работает, для каких-то - нет. В чём причина понять сразу не получилось. Требуется более глубокое исследование. Сейчас не досуг, да и, честно говоря, официально DaJet никогда не декларировал поддержку предопределённых значений справочников и планов видов характеристик.

Анализируя ошибку, вспомнил, что работу эту не закончил в своё время, но код оставил на будущее. Вот оно и аукнулось =) По итогу закостылил код таким образом, чтобы если будет ошибка, то просто предопределённые не прочитаются и всё. Короче говоря, перевёл критан в статус багофичи =)

[Исправление вот в этом коммите](https://github.com/zhichkin/dajet/commit/ca3438c0907a850a2e7a45115894b9c54130323a). Будет зарелизено в следующей версии DaJet 3.3.1. Пока что задачу закрываю.

Для работы с предопределёнными можно использовать следующий код. Там, где значение предопределённого будет **не равно пустому UUID** - это предопределённое значение, заданное в конфигураторе.
```sql
SELECT Ссылка, Код, Наименование, Предопределённый
  FROM Справочник.Тестовый
```
**Пример результата выполнения запроса выше:**
|**Ссылка**|**Код**|**Наименование**|**Предопределённый**|
|---------------|-------|-------|-------|
| {1297:08ec139d-a06b-a1b1-11ee-d58e96905585}| 000000001|Значение 1|b3b0fba1-3fba-821b-4209-0dc3299bd2da|
| {1297:08ec139d-a06b-a1b1-11ee-d58ed88f5361} | 000000002 |Значение 2|00000000-0000-0000-0000-000000000000|
