### ISSUE TITLE
[3.3.2] Создание видов

### ISSUE THREAD

**Issue by sacesare** [zhichkin/DaJet#7]
Есть некая проблема с созданием видов определенных типов перечислений.
При содании возвращаются ошибки:
```
"[СтатусыОбработкиМестФормированияПартийЗЕРНО] [_Enum91646] Неправильный синтаксис около конструкции \")\"."
"[СтатьиБезАналитики] [_Enum2292] Неправильный синтаксис около конструкции \")\"."
"[ТипыЗарубежныхПредприятий] [_Enum2348] Неправильный синтаксис около конструкции \")\"."

```

**Comment by zhichkin** [comment]
Нужно больше информации:
1. Тип СУБД.
2. Структура перечислений.
3. Файл скрипта для создания вьюх.

У сервиса **dbv** есть опция **генерации файла скрипта** для создания представлений (вьюх) СУБД. Этот файл генерируется без попытки сразу выполнить код SQL в СУБД. В этом файле можно найти сгенерированный для данных перечислений код SQL и посмотреть что с ним не так.

Иногда приходится дорабатывать скрипт для отдельных объектов вручную. Например, СУБД PostgreSQL имеет ограничение на длину наименований таблиц и их полей. "Из коробки" это 63 байта, если мне память не изменяет. То есть для кириллицы это 32 символа.

Попробуйте для начала сгенерировать файл скрипта SQL и сообщите, пожалуйста, о результатах.

**Comment by sacesare** [comment]
1. mssql
2. не очень понял...
3. все ошибки связаны с отсутвием значений для перечислений, аналогично слудующему скрипту:
```
CREATE VIEW [qqq].[Перечисление.СтатусыОбработкиМестФормированияПартийЗЕРНО] AS
SELECT e._EnumOrder AS [Порядок], t.[Имя], t.[Синоним], t.[Значение]
FROM _Enum91646 AS e INNER JOIN
(
.... здесь  пусто
) AS t ON e._IDRRef = t.[Значение];
```
Интересно, что далеко не для всех перечислений есть такая ошибка, а только для этих трех.

**Comment by zhichkin** [comment]
2. Структура перечисления - его значения. Например вот так:
![image](https://github.com/zhichkin/dajet/assets/10234025/0476ed54-0213-4a29-8b11-4f8e77939b99)

3. Очень странно... Давайте всё-таки структуру этих перечислений глянем.

А в скуле в таблице **_Enum91646** есть вообще что-нибудь ?

**Comment by zhichkin** [comment]
Создал в тестовой базе 1С пустое перечисление (без значений)
![image](https://github.com/zhichkin/dajet/assets/10234025/2e08d1ee-9b59-49d0-8981-07cec04e2bc4)

Сформировал файл скрипта для создания представлений СУБД. Получилось тоже самое, что и у вас.
Вывод - такое перечисление не нужно. Можно просто удалить этот код из скрипта и выполнить его в СУБД.
```SQL
IF OBJECT_ID(N'[dbo].[Перечисление.Перечисление1]', N'V') IS NOT NULL DROP VIEW [dbo].[Перечисление.Перечисление1];
GO
CREATE VIEW [dbo].[Перечисление.Перечисление1] AS
SELECT e._EnumOrder AS [Порядок], t.[Имя], t.[Синоним], t.[Значение]
FROM _Enum167 AS e INNER JOIN
(

-- у меня тут тоже пусто получилось =)

) AS t ON e._IDRRef = t.[Значение];
GO
```

**Comment by sacesare** [comment]
Да, вероятнее всего...хотя формально даже пустое перечисление где-то может использоваться- у него просто нет значений.
Ну, и в любом случае, желательно, что бы подобные моменты не прерывали выполнение скрипта по созданию видов)
Т.е. вопрос в том- считать это ошибкой( как сейчас), или тихо обрабатывать , создавая пустой вид, ну... или совсем не создавая его.

**Comment by zhichkin** [comment]
Я, как программист 1С с большим стажем, могу сказать, что пустое перечисление - это косяк. Вероятно они были созданы на будущее. Видимо его наступление затянулось =) Не знаю. Я так никогда не делаю и другим не советую.

По поводу сервиса **dbv** в платформе DaJet... Даже не знаю что сказать... Ну как-то не является он для меня приоритетным в плане развития. Минимальные потребности закрывает. Кроме того, аналогичные коммерческие продукты стоят в районе 200 000 рублей за лицензию. Не так дорого для средней организации...

Наверное поправлю падение скрипта как-нибудь на досуге. Не обещаю =) Просто я сам этим сервисом не пользуюсь от слова совсем. Коллег устраивает и в таком виде. Делал, честно говоря, просто "чтобы было".

Думаю, что вопрос исчерпан.
Спасибо за обращение! :heartpulse:
