### ISSUE TITLE
Обработка Json, полученных из HTTP-запроса

### ISSUE THREAD

**Issue by alex-bob-lip** [zhichkin/DaJet#8]
При работе с внешним API первым запросом идет авторизация. Этот запрос в версии Dajet Stream3.3.3 выполняется успешно. response.Code = 200 и response.Value = '{"token", "ghfkghfkjhgkjh"}".
Далее необходимо использовать данный токен в последующих запросах.   
Но в Dajet на текущий момент нет функции, позволяющей получить объект из строки json. 
Вариант синтаксиса:
Функция JSON_VALUE(strJSON, path) - Возвращает скалярное значение элемента JSON по пути path, приведенное к типу string.
 Например:
       `JSON_VALUE(@response.Value, "$.token") -- должна вернуть "ghfkghfkjhgkjh".`

```
DECLARE @json string = '[0, 1, 2]'
DECLARE @element string
@element = JSON_VALUE(@json, '$[0]') -- @element = '0'
```

**Comment by zhichkin** [comment]
По сути это реализация JSONPath или JSON Pointer. Предлагаю ориентироваться на это описание: https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-12.html

Конечно же полностью реализовывать стандарт я пока что не готов. Будем есть слона по частям =)

Название функции... может быть немного упростить/сократить ? Предлагаю: JPath по аналогии с XPath для XML.

**Comment by zhichkin** [comment]
Я так понимаю, что Вы больше ориентировались на функцию T-SQL ?
 https://learn.microsoft.com/ru-ru/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver16

**Comment by zhichkin** [comment]
Необходимо определиться вот с чем: DaJet имеет две среды выполнения скриптов. Одна среда, DaJet Studio, выполняет исключительно код СУБД, то есть SQL непосредственно в базе данных. Вторая среда выполнения, DaJet Stream, является гибридной, то есть частично это код на C#, а частично - SQL. Эти скрипты работают под управлением службы DaJet Stream Service и недоступны (пока во всяком случае) в среде DaJet Studio. Процессор скриптов DaJet Stream делает это прозрачным для пользователя, объединяя оба контекста: C# и SQL. 

Например, команда REQUEST выполняется в среде выполнения C#, а SELECT - в среде СУБД на SQL. Таким образом речь идёт о том для какой среды выполнения нужна функция JSON_VALUE, о которой Вы пишете. Судя по всему для DaJet Stream. Уточните этот момент, пожалуйста, или приведите пример полного скрипта для Вашего сценария использования.

Пример с DECLARE не совсем очевиден, так как блок объявления переменных в обоих процессорах скриптов обрабатывается по разному.

**Comment by alex-bob-lip** [comment]
> По сути это реализация JSONPath или JSON Pointer. Предлагаю ориентироваться на это описание: https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-12.html

Полная реализация наверное избыточна. Пока для экспериментов достаточно получения одного элемента по полному пути (для элемента массива по индексу, начинающемуся с нуля.
Я не особо знаю C#, но понимаю, что с JSON здесь работать не так просто, как в python или javascript.

> Я так понимаю, что Вы больше ориентировались на функцию T-SQL ?
https://learn.microsoft.com/ru-ru/sql/t-sql/functions/json-value-transact-sql?view=sql-server-ver16

Да, я ориентировался на эти функции (JSON_VALUE, JSON_QUERY, ISJSON, OPENJSON). И их вариации надо бы реализовать в контексте Dajet Stream на C#.

**Comment by alex-bob-lip** [comment]
> Необходимо определиться вот с чем: DaJet имеет две среды выполнения скриптов. Одна среда, DaJet Studio, выполняет исключительно код СУБД, то есть SQL непосредственно в базе данных. Вторая среда выполнения, DaJet Stream, является гибридной, то есть частично это код на C#, а частично - SQL. Эти скрипты работают под управлением службы DaJet Stream Service и недоступны (пока во всяком случае) в среде DaJet Studio. Процессор скриптов DaJet Stream делает это прозрачным для пользователя, объединяя оба контекста: C# и SQL.

Да, это я понимаю. На самом деле мне понравилось декларативное описание HTTP-запросов и обращений к Rabbit и Kafka. Оно легко читаетя и менее многословно, чем в процедурных языках. И не выглядит чем-то инородным рядом с запросами SQL.

> Например, команда REQUEST выполняется в среде выполнения C#, а SELECT - в среде СУБД на SQL. Таким образом речь идёт о том для какой среды выполнения нужна функция JSON_VALUE, о которой Вы пишете. Судя по всему для DaJet Stream. Уточните этот момент, пожалуйста, или приведите пример полного скрипта для Вашего сценария использования.

Да, это Dajet Stream. Пример скрипта пока не приведу (может позже). Опишу кейс интеграции. Есть база 1С во Fresh. К ней можно обращаться по интерфейсу OData. Есть СКУД (не 1С, система контроля управления доступом) с REST API. При оформлении приема на работу нового сотрудника нужно передать данные сотрудника для оформления пропуска. Передается ФИО, табельный номер, дата приема, должность, подразделение. 
При этом должности и подразделения - справочники в СКУД. Если должность не найдена в справочнике СКУД, то ее нужно добавить. Если подразделение не найдено в СКУД, то надо уведомить оператора об ошибке, чтобы он вручную ввел подразделение. Если сотрудник успешно зарегистрирован в СКУД. нужно записать его ID в дополнительный реквизит в справочник Сотрудники 1С.
Я это всё к чему - в рамках интеграции необходимо выполнять цепочки HTTP запросов с обработкой результатов (в виде JSON, XML, возможно yml, двоичных файлов и т.д.).  И если для _извлечения_  и _загрузки_ информации предлагаемый язык подходит хорошо, то для _обработки_ более подходящим видится какой-нибудь питон. 
Кстати, пришла в голову спонтанная идея использовать вспомогательный локальный микросервис для промежуточной обработки. Например [https://github.com/autumn-library/winow/tree/master](url) позволит писать обработчики на языке 1С, точнее onescript. Надо будет проверить.

**Comment by zhichkin** [comment]
Да, всё так оно и есть. Какой-то очень сложной логики реализация DaJet Stream не предполагала. Полноценная оркестрация http-сервисов тоже не планировалась. Тем не менее кое-какие мысли, например про простые саги, были =)

Ваш запрос принял. Нужно немного подумать и попробую реализовать что-то удобоваримое для дальнейшего обсуждения и развития. Вообще я планировал расширять функционал DaJet Stream при помощи пользовательских функций (UDF - user defined functions) в виде плагинов на C#. Я к этой теме с UDF ещё обязательно вернусь когда руки дойдут =) Ну а пока - JSON =)

Мысль с промежуточной обработкой при помощи, например ОСени, звучит интересно 👍

**Comment by zhichkin** [comment]
Пошаманил [немного](https://github.com/zhichkin/dajet/commit/03ca3ddaeca0a39b7da78a8e60f4c771bbcd0e3b). Код конечно же не идеальный, но с чего-то нужно начинать =)
Предварительно следующий ниже скрипт DaJet Stream работает. Релиз пока не делаю - нужно ещё тесты погонять, подумать что и как. Может быть Вы что-то подскажите.
Я сделал так, что при попытке получить значение свойства через точку процессор скрипта "смотрит" какой тип значения слева от точки. Если это **object**, то получает значение его свойства непосредственно, а если это **string**, то пытается сначала преобразовать его к типу **object**, десериализовав JSON.
Запилил селекторы для объектов типа **array** вида [индекс] и [name=123] - возвращает первое попавшееся значение **object**.
Схемы объектов, JSON и так далее не проверяю - получаю значения "на ходу" динамически.
Ну пока что вот так...
```SQL
DECLARE @id number = 3
DECLARE @response object -- HTTP ответ на запрос

REQUEST 'http://localhost/1c/hs/test/query'
   WITH User-Agent   = 'DaJet Stream'
      , Content-Type = 'text/plain; charset=utf-8'
 SELECT Method  = 'POST'    -- HTTP метод запроса
      , OnError = 'break'   -- break или continue
      , Content = 'Привет!' -- Тело HTTP запроса
   INTO @response -- { "Code": "200", "Value": "text" }

USE "mssql://zhichkin/dajet-exchange"

DECLARE @list array

          SELECT id = 0, name = 'name-0' INTO @list
UNION ALL SELECT id = 1, name = 'name-1'
UNION ALL SELECT id = 2, name = 'name-2'
UNION ALL SELECT id = 3, name = 'Say ' + @response.Value.Ответ

INSERT РегистрСведений.ВходящиеСообщения
SELECT НомерСообщения = VECTOR('so_incoming_queue')
     , Отправитель    = @list[id=@id].name
     , ТипСообщения   = @response.Value.list[id=2].name + ' (test)'
     , ТелоСообщения  = @response.Value.list[name='три'].name
     , ОтметкаВремени = NOW()
```

Значение свойства **Value** переменной **response** формирую вот таким вот кодом 1С в модуле http-сервиса:
```C#
СтруктураДанных = Новый Структура();
СтруктураДанных.Вставить("Ответ", "Привет");
МассивСтруктур = Новый Массив();
МассивСтруктур.Добавить(Новый Структура("id,name", 1, "раз"));
МассивСтруктур.Добавить(Новый Структура("id,name", 2, "два"));
МассивСтруктур.Добавить(Новый Структура("id,name", 3, "три"));	
СтруктураДанных.Вставить("list", МассивСтруктур);
```

Из http-сервиса 1С вот такой JSON прилетает:
```JSON
{
  "Ответ": "Привет",
  "list": [
    { "id": 1, "name": "раз" },
    { "id": 2, "name": "два" },
    { "id": 3, "name": "три" }
  ]
}
```

**Comment by zhichkin** [comment]
Реализовал всё то, о чём писал выше про JSON, в релизе [dajet-stream-svc-101](https://github.com/zhichkin/dajet/releases/tag/dajet-stream-svc-101). Просьба попробовать и дать обратную связь. Думаю, что какую-то часть Ваших потребностей это должно закрыть.

**Comment by alex-bob-lip** [comment]
Проверил, так работает.
Проверил также 2 случая:
1. `SELECT @response.Value.rows[id=1000].name` когда такого значения id нет в массиве. Выдает значение NULL.
2. Когда значение id есть в массиве, но значение name в json равно null (попалось в реальной выборке). Также выдает значение NULL.
Я думаю, это нормальное поведение и должно учитываться разработчиком с помощью проверки ISNULL()

**Comment by zhichkin** [comment]
Добрый день! Спасибо большое за обратную связь ❤️

> 1. `SELECT @response.Value.rows[id=1000].name` когда такого значения id нет в массиве. Выдает значение NULL.
>    Я думаю, это нормальное поведение и должно учитываться разработчиком с помощью проверки ISNULL()

В [языке запросов DaJet](https://zhichkin.github.io/dajet-query/index.html) (команды, выполняемые в контексте баз данных с точки зрения процессора скриптов **DaJet Stream**) функция **ISNULL(< expression >, < value >)** реализована уже очень давно. Там вообще много чего есть =) К сожалению, документация по ссылке уже немного устарела, там не всё есть, но, если установить платформу DaJet, то в поставке идёт полный набор скриптов с примерами всех возможностей языка запросов DaJet, реализованных на текущий момент.

В тоже самое время, для команды DaJet Stream **REQUEST** при вычислении выражений с участием объектов JSON реализовано **неявное преобразование значения типа NULL в пустую строку**.

Нижеследующий код демонстрирует оба варианта проверки на NULL в разных контекстах (C# и SQL):
```SQL
DECLARE @json     object
DECLARE @response object

USE "mssql://zhichkin/dajet-exchange"

SELECT value = '{ "test" : null }' INTO @json

REQUEST 'http://localhost/1c/hs/test/query'
 SELECT Method  = 'POST'
      , Content = CASE WHEN @json.value.test = '' THEN 'test is null' ELSE 'test has value' END
   INTO @response

INSERT РегистрСведений.ВходящиеСообщения
SELECT НомерСообщения = VECTOR('so_incoming_queue')
     , Отправитель    = 'DaJet'
     , ТипСообщения   = 'test'
     , ТелоСообщения  = ISNULL(@json.value.test, '@json.value.test IS NULL')
     , ОтметкаВремени = NOW()
```

**Comment by alex-bob-lip** [comment]
> В [языке запросов DaJet](https://zhichkin.github.io/dajet-query/index.html) (команды, выполняемые в контексте баз данных с точки зрения процессора скриптов **DaJet Stream**) функция **ISNULL(< expression >, < value >)** реализована уже очень давно. Там вообще много чего есть =) К сожалению, документация по ссылке уже немного устарела, там не всё есть, но, если установить платформу DaJet, то в поставке идёт полный набор скриптов с примерами всех возможностей языка запросов DaJet, реализованных на текущий момент.

Именно по скриптам и видео пытаюсь разбираться. Кстати, не нашел, есть ли в Dajet функция генерации нового UUID?

**Comment by zhichkin** [comment]
Функции генерации нового UUID, к сожалению, нет. И всё потому, что пока что не понял какую из них лучше использовать в PostgreSQL. Кроме того там надо плагин включать соответствующий. Возможно, что в сборке PostgreSQL для 1С этот плагин включён по умолчанию. Короче говоря, я пока отложил эту функцию на будущее, хотя там в общем-то не так много работы, чтобы её добавить.

А вот в контексте DaJet Stream нужно реализовывать функцию подобную DaJet.Json, например DaJet.NewUuid. Тоже не определился с дизайном пока что.
