### ISSUE TITLE
Вставка в таблицу с _SimpleKey

### ISSUE THREAD

**Issue by dothem2h** [zhichkin/DaJet#9]
При попытке вставке в таблицу с колонкой с _SimpleKey, возвращает ошибку:
Cannot insert the value NULL into column '_SimpleKey', table 'work.dbo._InfoRg26114'; column does not allow nulls. INSERT fails.

CREATE COMPUTED TABLE source AS
(
  SELECT '' AS abc
         5 AS ПопытокОсталось,
         '' AS СтрокаОшибок,
         'A1651579-29D4-440A-BF72-38EBE3BED6E6' AS _SimpleKey
)

INSERT РегистрСведений.ИнтернетКлиент FROM source

 _SimpleKey игнорируется и не добавляется к запросу.

**Comment by zhichkin** [comment]
Добрый день!

В старых версиях платформы 1С в регистрах сведений действительно есть служебное поле _SimpleKey. Вероятно я его не учёл при формировании команды INSERT.

Сообщите, пожалуйста, номер версии Вашей платформы 1С:Предприятие и режим совместимости конфигурации.

Текущим временным решением может быть добавление на уровне SQL Server значения по умолчанию для колонки _SimpleKey:
```SQL 
ALTER TABLE work.dbo._InfoRg26114
ADD CONSTRAINT my_constraint_name
DEFAULT NEWID()
FOR _SimpleKey;
```

Постараюсь добавить поддержку поля _SimpleKey для более старых платформ как можно скорее.

**Comment by dothem2h** [comment]
Там очень сильно кастомизированный конфиг, версия 8.3.13.1513
Временное решение к сожалению не подойдет, админские права напрочь отказываются давать.
Жду поддержку поля _SimpleKey, Спасибо!

**Comment by zhichkin** [comment]
Поле _SimpleKey использовалось в регистрах сведений на платформе 1С:Предприятие 8.2 и ниже.
Я так понимаю, что у Вас конфигурация работает в режиме совместимости 8.2.х.

**Comment by zhichkin** [comment]
Реализовано в релизе [DaJet 3.3.6](https://github.com/zhichkin/dajet/releases/tag/dajet-3.3.6)
Просьба проверить для своих сценариев использования и дать обратную связь.

**Пример использования (подробнее на странице релиза)**
> Использование COMPUTED TABLE (aka CTE - common table expression), как у вас, тоже возможно.
```SQL
DECLARE @simple_key uuid = SELECT NEWUUID()

INSERT РегистрСведений.ВходящаяОчередьСообщений
SELECT НомерСообщения   = VECTOR('so_inbox_queue')
     , Идентификатор    = @simple_key -- Тип значения "УникальныйИдентификатор" в 1С
     , ДатаВремя        = NOW()
     , Отправитель      = 'DaJet Studio'
     , ТипОперации      = 'INSERT'
     , ТипСообщения     = 'тест'
     , ТелоСообщения    = 'test'
     , ОписаниеОшибки   = ''
     , КоличествоОшибок = 0.0 -- Важно! Числовые значения в 1С - decimal или numeric !!!
     , SimpleKey        = NEWUUID() -- Переменная @simple_key или литерал 'a1651579-29d4-440a-bf72-38ebe3bed6e6'
```

**P.S.**
[Подробнее про функцию VECTOR](https://www.youtube.com/watch?v=s56E8OanUVQ&list=PLyBbhdsc7InutmVxyUszw-ZNJ5zKVBot2&index=3)
Если коротко, то это аналог **NEXT VALUE FOR** для получения очередного значения объекта **SEQUENCE** в MS SQL Server или функции **nextval** в PostgreSQL.
